USE [master]
GO

/****** Object:  Database [nyProject]    Script Date: 06/06/2024 1:06:26 SA ******/
CREATE DATABASE [nyProject]

go 

use [nyProject]

GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nyProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nyProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nyProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nyProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nyProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nyProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [nyProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nyProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nyProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nyProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nyProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nyProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nyProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nyProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nyProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nyProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nyProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nyProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nyProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nyProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nyProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nyProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nyProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nyProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [nyProject] SET  MULTI_USER 
GO

ALTER DATABASE [nyProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nyProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nyProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nyProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [nyProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [nyProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [nyProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [nyProject] SET  READ_WRITE 
GO


